FROM python:3.13-slim
LABEL description="Docker image for OpenFactory Virtual iVac"

ARG UNAME=ofa
ARG UID=1200
ARG GID=1200

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

RUN groupadd --gid $GID $UNAME
RUN useradd --create-home --uid $UID --gid $GID $UNAME
RUN apt-get update
RUN apt-get -y install git

# python dependencies
RUN pip install asyncua

WORKDIR /home/$UNAME
USER $UNAME
COPY ivac/adapter.py .
COPY ivac/virtual_ivac.py .
COPY ivac/ivac_server.py .
COPY opcua_server.py .

CMD ["python3", "-u", "adapter.py"]
