# Docker compose project for Virtual CNC Adapter
#
# Deploy the virtual adapter:
#   docker compose up -d
#
# Tear down the virtual adapter:
#   docker compose down

services:
  virtual-cnc-adapter:
    build:
      context: .
      dockerfile: Dockerfile
    image: ofa/cnc
    environment:
      - MIN_TOGGLE_TIME=2.0
      - MAX_TOGGLE_TIME=6.0
      - ADAPTER_PORT=7878
      - OPCUA_PORT=4840
      - NAMESPACE_URI=demofactory
      - DEVICE_BROWSE_NAME=IVAC
      - SERVER_IP=virtual-cnc-adapter
    networks:
      - factory-net

networks:

  factory-net:
    name: factory-net
    external: true
